### ISSUE TITLE
Stress and syllables splitting

### ISSUE THREAD

**Issue by umaxfun** [dmort27/epitran#124]
Hey,

Given a word ‘Scheinselbständigkeit’, Epitran transforms it to 'ʃaɪnsɛlbstæːndɪkkait’. 

And I need the result as [‘ʃaɪn’, ‘sɛlb’, ‘stæːn’, ‘dɪk’, ‘kait’] and somehow detect where the stress should be (at ‘ʃáɪn’ I think)

Is there a quick way to split the result into syllables and add stress?

**Comment by dmort27** [comment]
At present, there is no quick way of doing this.
