### ISSUE TITLE
import epitran shows an error

### ISSUE THREAD

**Issue by vampire-ab** [dmort27/epitran#135]
Hey, my team and I are using your excellent library for text conversion to phonemes for our research paper.
We are using google colab and when I import the library after installation, it returns the following error:

`Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-2-f681557d951c>"](https://localhost:8080/#), line 1, in <module>
    import epitran

  File "/usr/local/lib/python3.7/dist-packages/epitran/__init__.py", line 1, in <module>
    from epitran._epitran import Epitran

  File "/usr/local/lib/python3.7/dist-packages/epitran/_epitran.py", line 9, in <module>
    from epitran.simple import SimpleEpitran

  File "/usr/local/lib/python3.7/dist-packages/epitran/simple.py", line 116
    if nondeterminisms := self._non_deterministic_mappings(gr_by_line):
                        ^
SyntaxError: invalid syntax`

**Comment by ulf1** [comment]
yes i have the same bug what was added in commit https://github.com/dmort27/epitran/commit/954f12a1d4ab153593dd19d6ed1ca25ad6e3b835

**Comment by kalvinchang** [comment]
:= is only valid in Python 3.8+

**Comment by kalvinchang** [comment]
Could you update your Python version in colab (which defaults to 3.7)?

**Comment by dmort27** [comment]
In principle, we could use the old, more verose, syntax instead. Python 3.7 has not yet reached end of life, but it is quite old and more recent versions are better, if you can use them. Are you unable to work with >=3.8?

**Comment by ulf1** [comment]
I think it's a bad idea to assume >=3.8 for enforcing some new but secondary python syntax change

**Comment by vampire-ab** [comment]
> Could you update your Python version in colab (which defaults to 3.7)?

So, I did change the python version by following: [StackOverflow](https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version#:~:text=sudo%20update%2Dalternatives%20%2D%2Dconfig,and%20update%20the%20default%20python.)

This changed the python version but I'm no more able to use 'pip' for installation and a few queries similar to this at: [StackOverflow](https://stackoverflow.com/questions/64511066/python-3-9-pip-install). I have tried all solutions in the comments but I get such an error in return: 

`Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip'`

**Comment by vampire-ab** [comment]
> > Could you update your Python version in colab (which defaults to 3.7)?
> 
> So, I did change the python version by following: [StackOverflow](https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version#:~:text=sudo%20update%2Dalternatives%20%2D%2Dconfig,and%20update%20the%20default%20python.)
> 
> This changed the python version but I'm no more able to use 'pip' for installation and a few queries similar to this at: [StackOverflow](https://stackoverflow.com/questions/64511066/python-3-9-pip-install). I have tried all solutions in the comments but I get such an error in return:
> 
> `Traceback (most recent call last): File "/usr/local/bin/pip3", line 5, in <module> from pip._internal.cli.main import main ModuleNotFoundError: No module named 'pip'`

So, I used another method to perform the same. Referring to: [Site](https://www.datasciencelearner.com/change-python-version-in-google-colab-steps/)
This on running pip install epitran or !pip install epitran throws a new error:

`Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 29, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.9/distutils/__init__.py)`

**Comment by kalvinchang** [comment]
Our apologies for the inconvenience this has caused. 😞

**Comment by vampire-ab** [comment]
Since, lower versions weren't helping, changed to a higher version and this time switched to local. Local is not preferred as we need collaboration. Great library guys! I hope you work on older LTS version maintenance too! 
Thank You ✌

**Comment by kalvinchang** [comment]
We've created a new release that should be compatible with Python < 3.8 (#138)
I've tested the import on Colab and it should work
