### ISSUE TITLE
Bengali script sometimes leaves Bengali characters in transcriptions

### ISSUE THREAD

**Issue by jkunimune15** [dmort27/epitran#14]
IPA transliterations of Bengali characters with Chandrabindus in them leave the Chandrabindu there, when it should be replaced with a combining tilde, the corresponding IPA character. With epitran 0.56 installed:
~~~~python
>>> import epitran
>>> translator = epitran.Epitran('ben-Beng')
>>> translator.transliterate('হাঁ')
ɦaঁ
~~~~
I haven't checked extensively, but it is possible this also occurs with other languages and diacritics.

**Comment by dmort27** [comment]
Thanks for catching this. I'll check the other Indian languages.
