### ISSUE TITLE
Duplicated entries in ipa-xsampa.csv

### ISSUE THREAD

**Issue by liao961120** [dmort27/epitran#16]
I dowloaded [ipa-xsampa.csv](https://github.com/dmort27/epitran/blob/master/epitran/data/ipa-xsampa.csv) and find some errors in the data, e.g.
- `R\` in `X.SAMPA` maps to `vd uvular fricative` and  `vl uvular trill`
- `glottal plosive` has two identical rows

I modified them based on [wikipedia](https://en.wikipedia.org/wiki/X-SAMPA). I think you may like to check the modified file: [ipa-xsampa-modified.csv.txt](https://github.com/dmort27/epitran/files/2359100/ipa-xsampa-modified.csv.txt). Note that I modified the file according to my requirements, so it might not suit your needs.

Thanks for the data!

**Comment by dmort27** [comment]
Thank you for noticing this. Can you send me a pull request?

**Comment by dmort27** [comment]
I have merged your pull request. Thanks!
