### ISSUE TITLE
Incorrect transliteration of Yoruba /j/

### ISSUE THREAD

**Issue by jkunimune15** [dmort27/epitran#22]
It seems that Yoruba, which uses ⟨y⟩ for the approximant /j/, is being incorrectly transcribed such that ⟨y⟩ becomes the vowel /y/.

~~~~python
>>> import epitran
>>> translator = epitran.Epitran('yor-Latn')
>>> translator.transliterate('Yorùbá') # expected output: 'jōrùbá'
'yorùbá'
~~~~

**Comment by dmort27** [comment]
That's for this bug report. The problem is now corrected in the repo and will be fixed in the next release on PyPI.
