### ISSUE TITLE
backoff hanging at non-linguistic input

### ISSUE THREAD

**Issue by Ssloto** [dmort27/epitran#24]
Just testing this out for fun... one thing that I notice is that the backoff feature seems to hang if it gets some input that isn't in its alphabets, e.g.

>> epi = epitran.Epitran('tur-Latn')
>> epi.transliterate('merhaba: nasilsin?!')
'meɾhaba: nasilsin?!' 

works pretty quick (and would be better achieved if I had used an actual Turkish keyboard)

Wheras

>> backoff = Backoff(['tur-Latn', 'hin-Deva'])
>> backoff.transliterate('merhaba: nasilsin?!')

seems to hangs indefinitely...

Maybe backoff needs an extra something for pass-throughs? :)

**Comment by dmort27** [comment]
I'll fix this when I get the chance. I think this bug may have been introduced when we tried to make backoff work grapheme-by-grapheme instead of token-by-token.

**Comment by dmort27** [comment]
This is now fixed in the repo. I still haven't made a new release to PyPI.
