### ISSUE TITLE
Usage of BCP 47 tags with ASR systems

### ISSUE THREAD

**Issue by HughP** [dmort27/epitran#25]
I am curious to get a sense of what other researchers feel about the use of BCP47 tags for speech recognition models. And at what level (data ID, on training data, or the model itself, or out put from the model? Read more about BCP47 here: https://www.w3.org/International/articles/language-tags/
https://tools.ietf.org/html/bcp47

Some months ago I was on the IETF mailing list for sub-tags, and suggest that Speech to text and text to speech models should have tags identifying them. But there didn't seem to be any great "ah Ha's" from that crowd.

**Comment by dmort27** [comment]
I'm not sure I understand the relevance of this to Epitran.

**Comment by HughP** [comment]
Right, your response is ambiguous, and I would like to ask a clarifying question. 1. Is it that you feel that know what BCP 47 and feel it is not relevant to Epitran? or 2. You feel you don't understand BCP47 and  therefore can't make a judgment call?

**Comment by dmort27** [comment]
Your question seemed vague and spammy. Epitran is not an ASR model and was not sure why you were talking about it in that context. I am aware of BCP47, but I don't think it is relevant to Epitran.

**Comment by HughP** [comment]
Thanks for following up... The added information adds perspective.
BTW: I'm interested to see any other spam on the interwebs asking a
question about BCP47 — for professional reasons.

**Comment by HughP** [comment]
Does the output of Epitrans tag it's date with the't-' tag per: https://tools.ietf.org/html/rfc6497

**Comment by dmort27** [comment]
No. This would be highly undesirable from the standpoint of Epitran's primary use cases.
