### ISSUE TITLE
List of all ipa characters used for English and Polish

### ISSUE THREAD

**Issue by Adnane017** [dmort27/epitran#27]
Hi David,

Is there a way to directly get the list of all ipa symbols that you use for English and Polish? 

Thanks,
Adnane

**Comment by dmort27** [comment]
Hi Adnane,

There is no way of obtaining this information directly. However, you can get the relevant information from pol-Latn.csv and arpabet.csv.

Best,
David

**Comment by Adnane017** [comment]
Thanks!

**Comment by Adnane017** [comment]
Hi David,

A quick question related to the above. What do the words 'pau' and 'null' at the start of the file arpabet.csv mean?

Cheers,
Adnane

**Comment by ArtemisZGL** [comment]
@Adnane017 @dmort27 hello, I also have some questions about the ipa characters, what's the different in pol-Latn.csv and arpabet.csv ? Is that all support languages has its own map csv file? Or can we get the separate symbols of the transliterate method instead concatenating them together in one word?
