### ISSUE TITLE
Meaning of the words 'pau' and 'null' at the start of the file arpabet.csv 

### ISSUE THREAD

**Issue by Adnane017** [dmort27/epitran#30]
Hi David,

Related to the issue I rose on the 13th May 2019 (list of all ipa characters used for English and Polish), What do the words 'pau' and 'null' at the start of the file arpabet.csv mean?

Cheers,
Adnane

**Comment by dmort27** [comment]
'pau' is ARPAbet for "pause". 'null' is for empty segments.

**Comment by dmort27** [comment]
In principle, neither of these should occur in the output of flite's lex_lookup.

**Comment by Adnane017** [comment]
Ok nothing to worry about then. Thanks
