### ISSUE TITLE
EpihanTraditional Class does not have regexp attribute

### ISSUE THREAD

**Issue by justhalf** [dmort27/epitran#33]
When running `Backoff` class with "cmn-Hant" (which uses `EpihanTraditional`), it complains with the following error:

    File "/usr2/home/amuis/anaconda3/envs/py36/lib/python3.6/site-packages/epitran/backoff.py", line 46, in transliterate
        m = lang.epi.regexp.match(dia.process(token))
    AttributeError: 'EpihanTraditional' object has no attribute 'regexp'

This can be easily fixed by adding the following line at the end of https://github.com/dmort27/epitran/blob/master/epitran/epihan.py

    self.regexp = re.compile(r'\p{Han}')

I assume the character class "\[{Han}" captures both traditional and simplified Chinese.

**Comment by dmort27** [comment]
Thanks for catching this. I've made this change in the repo, which will be reflected in the next release.
