### ISSUE TITLE
word_to_tuples AttributeError for eng-Latn

### ISSUE THREAD

**Issue by MarkKoz** [dmort27/epitran#37]
It happens here because the function `panphon.FeatureTable.segs` isn't defined:

https://github.com/dmort27/epitran/blob/master/epitran/flite.py#L155

Using Python 3.7.4. This is the output of `pip freeze`:

```
editdistance==0.5.3
epitran==1.1
marisa-trie==0.7.5
munkres==1.1.2
numpy==1.17.0
panphon==0.15
PyYAML==5.1.2
regex==2019.8.19
unicodecsv==0.14.1
```

**Comment by dmort27** [comment]
@MarkKoz I believe this has been fixed in GitHub. Please test it and see if this is the case.

**Comment by MarkKoz** [comment]
Thanks! The error is indeed gone now.
