### ISSUE TITLE
Attribute error :module 'epitran' has no attribute 'Epitran'

### ISSUE THREAD

**Issue by jey07** [dmort27/epitran#43]
Hi I am getting attribute error. 
To give a background, i installed in my environment in conda and from there i ran setup.py .

![image](https://user-images.githubusercontent.com/13083382/74533533-1e16ef00-4f32-11ea-88a1-88b332104c52.png)

I am using jupyter notebook

**Comment by dmort27** [comment]
How did you fix it?

**Comment by jey07** [comment]
It required MV c++ 14.0 version but

**Comment by larsAfl** [comment]
Note that the file shouldn´t have the same name as the import.

**Comment by dmort27** [comment]
@jey07 I don’t have access to Visual Studio so I don’t have a good way of debugging this.  It seems to be an issue with Marisa-trie rather than with Epitran specifically.

**Comment by jey07** [comment]
I had similar issue. Tried  various stuff but could not figure it  out.  At
the end , I switched to ubuntu. Epitran worked well.

**Comment by jey07** [comment]
Moved to ubuntu. No longer a problem
