### ISSUE TITLE
Different IPA with punctuation in German

### ISSUE THREAD

**Issue by trenslow** [dmort27/epitran#47]
Hello all,

First off I wanted to say well done on Epitran! It is a tool that has proven useful for many projects of mine.

I stumbled across something today and I wanted to know if Epitran was designed to do this, or if it's a bug. I noticed that when I transliterate words in German, they have a different IPA transliterations when adding punctuation. As far as I can tell, this doesn't happen in any other language (I tried to reproduce the error in Polish, Russian and English.).

Examples: 

- transliterate('heute') -> 'hoytə' but transliterate('heute?') -> 'hoy**h**te?'
- transliterate('Tag') -> 'tak' but transliterate('Tag!') -> 'ta**ɡ**!'
- transliterate('Ende') -> 'əndə' but transliterate('Ende.') -> 'ənd**e**.'

For the last two examples, I could accept the transliterations that are produced when punctuation is added to the string, when phonetic environment and dialect are taken into consideration. However, to my knowledge, I don't know of any case where 'heute' should have an 'h' after the diphthong in its transliteration.

When using the transliterate function, I normally use normpunc=True and ligatures=True, but even disabling those flags produces the same results. I also used pip to check that I was using the latest version of Epitran.

I would really appreciate some info on this matter, as it will guide my future projects. Thanks a lot for your time!

**Comment by dmort27** [comment]
For _Tag_ and _Ende_, Epitran is behaving as expected. It expects inputs as tokens and assumes that the beginning and end of token strings are word boundaries. Since some patterns make reference to word boundaries, trailing punctuation interferes with these rules. I'm not sure yet what is going on with _heute_, but this is clearly a bug. I'll look into it.

**Comment by trenslow** [comment]
Hi David, thanks so much for the prompt response! I now understand the behavior I experienced and know how to work with it on my side.

Still it's a bit strange to me that trailing punctuation only interferes with the rules in German (as far as I can tell, as I didn't check all the languages exhaustively). I guess it all depends on how the rules are written in the different languages.

Looking forward to hearing your feedback on the _heute_ bug!

**Comment by dmort27** [comment]
The _heute_ bug is now fixed. The problem was that the mechanism that maps _eu_ to _oy_ applies after the mechanism that maps short _u_ to _uh_ (a rule that was too general, so it applied to _eu_). This is now fixed.

**Comment by trenslow** [comment]
Aha, that makes sense! Thanks a lot for the quick fix. Epitran rocks :)
