### ISSUE TITLE
Bad cyrrillic simbols sometimes

### ISSUE THREAD

**Issue by PasaOpasen** [dmort27/epitran#50]
So I use this code:

```python
from epitran.backoff import Backoff

backoff = Backoff(['fas-Arab', 'rus-Cyrl'])
                  
backoff.transliterate('Привет дорогой друг пидор')
```
 and it gives 

```
'prʲivʲet doroɡoй druɡ pʲidor'
```

as u see, there is the russian **й** in result, which should be (maybe) **j**. Or am I wrong?

**Comment by dmort27** [comment]
You are not wrong. There is a bug somewhere in `Backoff` (this is not a problem for `epitran.transliterate`). Also, you should present input to Epitran token-by-token rather than as a series of whitespace-delimited tokens, as this will sometimes produce the wrong result.

**Comment by PasaOpasen** [comment]
Yes, this is not a problem for `epitran.transliterate`, it's okay
