### ISSUE TITLE
question about machine learning in this framework

### ISSUE THREAD

**Issue by matanster** [dmort27/epitran#51]
Is it correct to understand from the paper, that no machine learning is involved or directly integrated in the framework that epitran is? or could you point me in the right direction?

**Comment by dmort27** [comment]
You are correct that almost all Epitran modules do not use any machine learning—they are purely rule-based. The exception is English, which uses the WFST-based G2P engine from the Flite speech synthesis system (which is trained on a pronouncing dictionary). In principle, Flite could be used to support other languages for which freely available pronouncing dictionaries are available.
