### ISSUE TITLE
When i use epitran--English - Latn, it tells that root:lex_lookup (from flite) is not installed. But I have installed lex_lookup

### ISSUE THREAD

**Issue by JonneryR** [dmort27/epitran#58]
When i use epitran--English - Latn, it tells that root:lex_lookup (from flite) is not installed. But I have installed lex_lookup.

(base) [root@host-10-29-0-161 testsuite]# make lex_lookup
Makefile:83: warning: overriding recipe for target `multi_thread'
Makefile:80: warning: ignoring old recipe for target `multi_thread'
make: `lex_lookup' is up to date.

Error:
>>> import epitran
>>> epi = epitran.Epitran('eng-Latn')
>>> print(epi.transliterate(u'Berkeley'))
WARNING:root:lex_lookup (from flite) is not installed.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/huawei/data1/z00574176/G2P/git_reproduced/epitran-master/epitran/_epitran.py", line 62, in transliterate
    return self.epi.transliterate(word, normpunc, ligatures)
  File "/opt/huawei/data1/z00574176/G2P/git_reproduced/epitran-master/epitran/flite.py", line 96, in transliterate
    acc.append(self.english_g2p(chunk))
  File "/opt/huawei/data1/z00574176/G2P/git_reproduced/epitran-master/epitran/flite.py", line 214, in english_g2p
    arpa_text = arpa_text.splitlines()[0]
IndexError: list index out of range

**Comment by dmort27** [comment]
I does not appear that you have copied `lex_lookup` to a place in your path. To test, try entering `lex_lookup` at the command line.

**Comment by JonneryR** [comment]
> I does not appear that you have copied `lex_lookup` to a place in your path. To test, try entering `lex_lookup` at the command line.
When I tried to enter lex_lookup, this message appeared.
bash: lex_lookup: command not found

**Comment by JonneryR** [comment]
> I does not appear that you have copied `lex_lookup` to a place in your path. To test, try entering `lex_lookup` at the command line.

I find the problem, the path which I used is wrong. I have to use '/usr/bin'. Thanks!
