### ISSUE TITLE
In French, the final 's' should be silent, 'es' shouldn't after a consonant

### ISSUE THREAD

**Issue by rezemika** [dmort27/epitran#6]
Hello, I just discoverd this awesome module, and I found two issues with the French language (both with `fra-Latn` and `fra-Latn-np`).

## Final 's'

When a word ends with a 's', the 's' is silent. So "il" ("he / she") is pronounced in the same way as "ils" ("they"). However, when I try `epi.transliterate("il")` and `epi.transliterate("ils")`, it returns `il` and `ils`.

## Final 'es'

The final 'es' is pronounced when it comes after a consonant. For example, "faites" ("do") is pronounced "fɛt" and "fait" ("done") is pronounced "fɛ". But `transliterate()` returns "fe" and "fe".

In the same way, it returns "ɡaraʒ" for "garage" (which is correct, Wikitionary gives "ɡa.ʁaʒ") but "ɡara" for "garages".

**Comment by dmort27** [comment]
I'll look in to fixing these problems. If you can generate more test data for French, it would be helpful to me in improving French support.

**Comment by rezemika** [comment]
Of course. Here are some words ready for testing. I'll see if I can generate them automatically from Wikitionary.

## Final 's'

```python3
# "Il" / "Ils"
self._derivation('il', 'il')
self._derivation('ils', 'il')

# "Fusil"
self._derivation('fusil', 'fy.zi')
self._derivation('fusils', 'fy.zi')

# "Œuf"
self._derivation('œuf', 'œf')
self._derivation('œufs', 'œf')  # Many French people pronounce "ø", but this one is valid too.

# "Décret"
self._derivation('décret', 'de.kʁɛ')
self._derivation('décrets', 'de.kʁɛ')

# "Loi"
self._derivation('loi', 'lwa')
self._derivation('lois', 'lwa')
```

## Final 'es'

```python
# "Dame"
self._derivation('dame', 'dam')
self._derivation('dames', 'dam')

# "Garage"
self._derivation('garage', 'ɡa.ʁaʒ')
self._derivation('garages', 'ɡa.ʁaʒ')

# "Faire" verb
self._derivation('fait', 'fɛ')
self._derivation('faits', 'fɛ')
self._derivation('faites', 'fɛt')

# "Homme"
self._derivation('homme', 'ɔm')
self._derivation('hommes', 'ɔm')

# "Personne"
self._derivation('personne', 'pɛʁ.sɔn')
self._derivation('personnes', 'pɛʁ.sɔn')
```

**Comment by dmort27** [comment]
I believe this is fixed now. Please have a look.
