### ISSUE TITLE
Can we convert the IPA back to the language token?

### ISSUE THREAD

**Issue by ArtemisZGL** [dmort27/epitran#63]
Thanks for your great job firstly ! It's a really awesome project ! And I have a question about how to convert the ipa token to the language token ? Or is it possible ?

**Comment by ArtemisZGL** [comment]
I saw some code about that in the source code, like "general_reverse_trans", but can't find the map csv file with "_rev" also the readme about the func, is that this feature still not well construct?

**Comment by dmort27** [comment]
In general, this doesn't work. It has only be implemented for Russian and will only *ever* work for languages where their is an unambiguous phonemic->orthographic mapping (which is rarer than an unambiguous orthographic->phonemic mapping). Consider the case of French: G2P is possible (though the G2P implementation for French in Epitran is buggy); P2G, without context and a data-driven approach, is completely implausible.
