### ISSUE TITLE
flite and t2p are provided in Ubuntu packages

### ISSUE THREAD

**Issue by tats-u** [dmort27/epitran#67]
You can install `flite` by `sudo apt install flite`.  `t2p` is included.

https://packages.ubuntu.com/search?keywords=flite&searchon=names&exact=1&suite=all&section=all

```
$ dpkg -S /usr/bin/t2p
flite: /usr/bin/t2p
$ flite --version
  Carnegie Mellon University, Copyright (c) 1999-2016, all rights reserved
  version: flite-2.1-release Dec 2017 (http://cmuflite.org)
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

`lex_lookup` must be still built from source.

**Comment by dmort27** [comment]
`t2p` is no longer supported. Mention of it needs to be eliminated from the codebase, README

**Comment by tats-u** [comment]
Thank you for your reply.
I suppose that we do not have to `sudo make install` `flite` itself (not `lex_lookup`).

**Comment by dmort27** [comment]
That should be correct.

**Comment by tats-u** [comment]
Is “that” mean to install source-built flite itself?
