### ISSUE TITLE
Regex + rules difference between [] and ().

### ISSUE THREAD

**Issue by OrderAndCh4oS** [dmort27/epitran#70]
In fra-Latn.txt preprocessors there are some matches that use `[]` and others that use `()`

```
::vowel:: = a|á|â|æ|e|é|è|ê|ë|i|î|ï|o|ô|œ|u|ù|û|ü|A|Á|Â|Æ|E|É|È|Ê|Ë|I|Î|Ï|O|Ô|Œ|U|Ù|Û|Ü|ɛ
::front_vowel:: = e|é|è|ê|ë|i|î|ï|y|E|É|È|Ê|Ë|I|Î|Ï|Y|ɛ
::consonant:: = b|ç|c|ch|d|f|g|j|k|l|m|n|p|r|s|t|v|w|z|ʒ
```

```
% Treatment of <c> and <s>
sc -> s / _ [::front_vowel::]
c -> s / _ [::front_vowel::]

% High vowels become glides before vowels
ou -> w / _ (::vowel::)
u -> ɥ / _ (::vowel::)
```
Is a difference in behaviour between the two?

Am I right in thinking that:

-  `[::front_vowel::]` is `[e|é|è|ê|ë|i|î|ï|y|E|É|È|Ê|Ë|I|Î|Ï|Y|ɛ]` in regex.
-  `(::front_vowel::)` is `(e|é|è|ê|ë|i|î|ï|y|E|É|È|Ê|Ë|I|Î|Ï|Y|ɛ)` in regex.

From what I understand of regex they look as though they'd do the same thing, except `[::front_vowel::]` would also match the `|` char. 

I also don't think `[]` would work if there are two or more chars in a group, for example `ch` in:

```
::consonant:: = b|ç|c|ch|d|f|g|j|k|l|m|n|p|r|s|t|v|w|z|ʒ
```

I'd guess that `()` also create capturing groups but I'm not sure if that's being utilised. 

Any guidance would be greatly appreciated.

**Comment by dmort27** [comment]
These are artifacts of an earlier time. square brackets should be replaced by parentheses.

**Comment by OrderAndCh4oS** [comment]
Thank you so much for clearing that up. I suspected that was the case, just wanted to make sure I hadn't overlooked something.  

Superb project, by the way, has been a great help.
