### ISSUE TITLE
FileNotFoundError chinese.csv 

### ISSUE THREAD

**Issue by krigeta** [dmort27/epitran#76]
Hello, what is the solution for this error?

```
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/epitran/simple.py in _load_g2p_map(self, code, rev)
     90         except IndexError:
     91             raise DatafileError('Add an appropriately-named mapping to the data/maps directory.')
---> 92         with open(path, 'rb') as f:
     93             reader = csv.reader(f, encoding='utf-8')
     94             orth, phon = next(reader)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/epitran/data/map/chinese.csv'
```

**Comment by dmort27** [comment]
There is no Epitran mode called `chinese'. I think you probably want `cnm-Hans` or `cnm-Hant`.

**Comment by dmort27** [comment]
Please provide a minimal example that reproduces the error, and I'll show you what to do differently.

**Comment by krigeta** [comment]
Hello sir, I am trying to run this [repo](https://github.com/Tomiinek/Multilingual_Text_to_Speech) and trying to run [this](https://github.com/Tomiinek/Multilingual_Text_to_Speech/blob/caa65277b914346d12a04cdbee799585ba1e48ce/dataset/dataset.py#L193) method and as soon as I run this method I am getting this error.

**Comment by dmort27** [comment]
You are still not providing the information I need. Please provide an *actual code example* so I can see how you are calling the method (with what arguments, etc.).

**Comment by krigeta** [comment]
Actually its the code which is using it so I have some folders de,fr,nl,ru and zh so which mapping should be correct for them?

**Comment by dmort27** [comment]
I have know way of knowing what you are talking about. If you don't provide me with a minimal example that yields the error message, I have no way of knowing:

1. Whether the error is a problem with Epitran, some other software package, or your code.
2. How to fix the problem

Since you have not be willing to provide such an example, I am unable to help you.
