### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by jplumail** [dmort27/epitran#88]
Hi !

I got a regex error when using the french language. I think it comes from a bug at [this line](https://github.com/dmort27/epitran/blob/master/epitran/data/pre/fra-Latn.txt#L67);

I fixed it by changing 
```
dd -> 0 / ()::vowel::|n) _ #
```
to
```
dd -> 0 / (::vowel::|n) _ #
```

**Comment by dmort27** [comment]
Thanks, @jplumail . It's now fixed in the GitHub repo. I'll make a new PyPI package soon.
