### ISSUE TITLE
Extraneous unicode character in Kazakh

### ISSUE THREAD

**Issue by emilyahn** [dmort27/epitran#89]
Hi David and team,

When I use the Kazakh package and am transliterating this character: "ү", the output produces spurious \x08 (twice) before the expected "ʏ". Here's an example:
```
>>> epi.transliterate(u'түзде')
't\x08\x08ʏzdje'
```

**Comment by emilyahn** [comment]
Ah, `kaz-Cyrl`

**Comment by dmort27** [comment]
I was able to replicate the error and correct it (locally, at least). I have entered the second stage of coding.

- **Stage 1:** My code isn't working and I don't know why!
- **Stage 2:** My code is working and I don't know why!

The updated version in in the GitHub repo. I'll make a new PyPI release in the next few days.
