### ISSUE TITLE
Citing Epitran

### ISSUE THREAD

**Issue by Adamits** [dmort27/epitran#9]
Hi!

I used this library for some work that I am writing a paper on. Is there something that I can cite? I should note that I also used Panphon and cited appropriately from the paper linked in that README.

**Comment by dmort27** [comment]
Hi!

Thanks for using Epitran. You should cite the following paper:

@InProceedings{Mortensen-et-al:2018,
  author = {David R. Mortensen and Siddharth Dalmia and Patrick Littell},
  title = {Epitran: Precision G2P for Many Languages},
  booktitle = {Proceedings of the Eleventh International Conference on Language Resources and Evaluation (LREC 2018)},
  year = {2018},
  month = {may},
  date = {7-12},
  location = {Miyazaki, Japan},
  editor = {Nicoletta Calzolari (Conference chair) and Khalid Choukri and Christopher Cieri and Thierry Declerck and Sara Goggi and Koiti Hasida and Hitoshi Isahara and Bente Maegaard and Joseph Mariani and Hélène Mazo and Asuncion Moreno and Jan Odijk and Stelios Piperidis and Takenobu Tokunaga},
  publisher = {European Language Resources Association (ELRA)},
  address = {Paris, France},
  isbn = {979-10-95546-00-9},
  language = {english}
  }

Soon, I'll add that information to the README.
